version: "3"
services:
  postgres_kamon:
    container_name: postgres_kamon
    image: postgres:15.2
    environment:
      POSTGRES_DB: kamon_db
      POSTGRES_USER: postgres-kamon
      POSTGRES_PASSWORD: test
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  kamon_server:
    container_name: kamon_server
    build:
      context: ./
    ports:
      - 80:3000
    depends_on:
      postgres_kamon:
        condition: service_healthy

  postgrest:
    image: postgrest/postgrest
    ports:
      - "3001:3001"
    environment:
      PGRST_DB_URI: postgres://postgres-kamon:test@db:5432/kamon_db
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3001
    depends_on:
      postgres_kamon:
        condition: service_healthy

volumes:
  postgres:
