version: "3"
services:
  kamon_postgres:
    container_name: kamon_postgres
    image: postgres:15.2
    environment:
      POSTGRES_DB: kamon_db
      POSTGRES_USER: postgres-kamon
      POSTGRES_PASSWORD: test
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres:
