# see https://blog.benoitblanchon.fr/github-action-run-ssh-commands/
name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create SSH key
      run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/aws.key
          chmod 600 ~/.ssh/aws.key
          cat >>~/.ssh/config <<END
          Host aws
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/aws.key
            StrictHostKeyChecking no
          END
      shell: bash
      env:
          SSH_USER: ${{ secrets.AWS_SSH_USER }}
          SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
          SSH_HOST: ${{ secrets.AWS_SSH_HOST }}

    - name: Deploy
      run: ssh aws 'cd ~/kamon && git pull && docker compose stop && docker compose build && docker compose up -d'
