name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: make install

      - name: Building CLI
        run: make build-cli
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: make install

      - name: Run CLI tests
        run: make test-cli

      - name: Run Webapp unit tests
        run: make test-webapp

      - name: Run Webapp e2e tests
        run: make e2e-test-webapp

