name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: make install

      - name: Building CORE
        run: make build-core

      - name: Building CLI
        run: make build-cli

      - name: Building Web App
        run: make build-webapp

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: make install

      - name: Building CORE
        run: make build-core

      - name: Run CORE tests
        run: make test-core

      - name: Run CLI tests
        run: make test-cli

      - name: Run postgres docker
        run: docker-compose -f "docker-compose.dev.yml" up -d --build

      - name: Checking container
        run: docker ps -a

      - name: Run Webapp unit tests
        run: make unit-test-webapp

      - name: Run Webapp e2e tests
        run: make e2e-test-webapp
        env:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres-kamon
          POSTGRES_PASSWORD: test
          POSTGRES_DATABASE: kamon_db
